### ISSUE TITLE
TypeError: Cannot read property 'parse' of undefined

### ISSUE THREAD

**Issue by kaliseo** [NativeScript/nativescript-ui-feedback#1313]
Hi,

RadListView seems to crash on ObservableArray
Plugin version : nativescript-ui-listview@8.0.1
Platform version : Android v6.1.2

Code sample : 
`viewModel.set("playlists", new ObservableArray());
    viewModel.playlists.push({
      name: "test"
    });`

N.B. Removing push does not trigger error, it seems ui-listview is unable to parse ObservableArray.

Template : 
`<lv:RadListView items="{{ playlists }}" >
            <lv:RadListView.itemTemplate>
                <StackLayout orientation="vertical">
                    <Label fontSize="20" text="{{ name }}"/>
                </StackLayout>
            </lv:RadListView.itemTemplate>
        </lv:RadListView>`

Trace : 
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateViewHolder failed
System.err: TypeError: Cannot read property 'parse' of undefined
System.err: 
System.err: StackTrace:
System.err:     push.../node_modules/nativescript-ui-listview/ui-listview.common.js.RadListView.resolveTemplateView(file:///node_modules/nativescript-ui-listview/ui-listview.common.js:532:0)
System.err:     at push.../node_modules/nativescript-ui-listview/ui-listview.common.js.RadListView.getViewForViewType(file:///node_modules/nativescript-ui-listview/ui-listview.common.js:579:0)
System.err:     at ListViewAdapter.onCreateViewHolder(file:///node_modules/nativescript-ui-listview/ui-listview.js:129:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err:     at com.tns.gen.com.telerik.widget.list.ListViewAdapter_vendor_1806_32_ListViewAdapter.onCreateViewHolder(ListViewAdapter_vendor_1806_32_ListViewAdapter.java:41)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:468)
System.err:     at com.telerik.widget.list.ListViewWrapperAdapter.onCreateViewHolder(ListViewWrapperAdapter.java:20)
System.err:     at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
System.err:     at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err:     at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
System.err:     at com.telerik.widget.list.RadListView.onMeasure(RadListView.java:609)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:956)
System.err:     at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:754)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:847)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.VerticalScrollView.onMeasure(VerticalScrollView.java:147)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1535)
System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:825)
System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:704)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6758)
System.err:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
System.err:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:717)
System.err:     at android.view.View.measure(View.java:23355)
System.err:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2919)
System.err:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1749)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2042)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1637)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7797)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1172)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:984)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:809)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1158)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6898)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by NickIliev** [comment]
@kaliseo why using ObservableArray in the first place?

Still, I've tried to reproduce the issue but the **push** is working on my side - perhaps you could provide a demo project?
