### ISSUE TITLE
RadPieChart java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by quinnban** [NativeScript/nativescript-ui-feedback#1324]
> Please take a minute to read our [NativeScript Code of Conduct](https://github.com/NativeScript/codeofconduct) before proceeding with posting issues or discussing. The purpose of this guide is to make communication and cooperation within our forums a pleasure for you and the other members.

## Please, provide the details below:
 When using the RadPieChart  the application crashes the stacktrace is as following:

System.err: An uncaught Exception occurred on "main" thread.
System.err: The value for normalizedValue is not valid! The possible values are in the [0, 1] interval.
System.err: 
System.err: StackTrace:
System.err: java.lang.IllegalArgumentException: The value for normalizedValue is not valid! The possible values are in the [0, 1] interval.
System.err:     at com.telerik.widget.chart.engine.dataPoints.PieDataPoint.update(PieDataPoint.java:121)
System.err:     at com.telerik.widget.chart.engine.series.PieSeriesModel.updateDataPoints(PieSeriesModel.java:142)
System.err:     at com.telerik.widget.chart.engine.series.PieSeriesModel.arrangeOverride(PieSeriesModel.java:98)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:185)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:166)
System.err:     at com.telerik.widget.chart.engine.chartAreas.ChartPlotAreaModel.arrangeOverride(ChartPlotAreaModel.java:64)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:185)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:166)
System.err:     at com.telerik.widget.chart.engine.chartAreas.ChartPlotAreaModel.arrange(ChartPlotAreaModel.java:72)
System.err:     at com.telerik.widget.chart.engine.chartAreas.ChartAreaModel.arrangeOverride(ChartAreaModel.java:174)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:185)
System.err:     at com.telerik.widget.chart.engine.elementTree.ChartNode.arrange(ChartNode.java:166)
System.err:     at com.telerik.widget.chart.visualization.common.RadChartViewBase.updateChartArea(RadChartViewBase.java:941)
System.err:     at com.telerik.widget.chart.visualization.common.RadChartViewBase.arrangeOverride(RadChartViewBase.java:633)
System.err:     at com.telerik.widget.chart.visualization.common.RadChartViewBase.onMeasure(RadChartViewBase.java:515)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
System.err:     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
System.err:     at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
System.err:     at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:87)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:87)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
System.err:     at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:87)
System.err:     at android.view.View.measure(View.java:24530)
System.err:     at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9119)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1583)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
System.err:     at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
System.err:     at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
System.err:     at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
System.err:     at com.telerik.widget.list.RadListView.onLayout(RadListView.java:600)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:354)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.ContentLayout.onLayout(ContentLayout.java:73)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err:     at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:178)
System.err:     at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:132)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
System.err:     at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
System.err:     at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
System.err:     at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
System.err:     at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
System.err:     at android.view.View.layout(View.java:21912)
System.err:     at android.view.ViewGroup.layout(ViewGroup.java:6260)
System.err:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3080)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2590)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:790)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:725)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
System.err:     at android.os.Handler.handleCallback(Handler.java:883)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

### Which platform(s) does your issue occur on?
Android 

### Please provide the following version numbers that your issue occurs with:

 "tns-android": {
      "version": "6.2.0"
    },
  "nativescript-ui-chart": "7.1.1",
  "tns-core-modules": "6.3.2",

### Please tell us how to recreate the issue in as much detail as possible.
1. start application

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

`<RadPieChart allowAnimation="true"  row="1" col="0" colSpan="12" id="chart" backgroundColor="#292929" (pointSelected)="onSelected($event)" (pointDeselected)="onDeselected($event)" #chart>
                <DonutSeries tkPieSeries
                    seriesName="pie"
                    showPercentage="true"
                    selectionMode="DataPoint"
                    expandRadius="0.4"
                    outerRadiusFactor="0.7"
                    innerRadiusFactor="0.4"
                    valueProperty="grainVol"
                    legendLabel="grainName"
                    [items]="chartData.chart"></DonutSeries>
                <Palette tkPiePalette seriesName="pie">
                        <PaletteEntry tkPiePaletteEntry fillColor="#EB5E55" strokeColor="#da251a"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#D81E5B" strokeColor="#95153f"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#FDF0D5" strokeColor="#fad68c"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#C6D8D3" strokeColor="#99b9b0"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#00FDDC" strokeColor="#00b199"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#495F41" strokeColor="#263222"></PaletteEntry>
                </Palette>
                <Palette tkPiePalette seriesName="pie" seriesState="Selected">
                        <PaletteEntry tkPiePaletteEntry fillColor="#da251a" strokeColor="#da251a"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#95153f" strokeColor="#95153f"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#fad68c" strokeColor="#fad68c"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#99b9b0" strokeColor="#99b9b0"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#00b199" strokeColor="#00b199"></PaletteEntry>
                        <PaletteEntry tkPiePaletteEntry fillColor="#263222" strokeColor="#263222"></PaletteEntry>
                 </Palette>  
                 <RadLegendView tkPieLegend backgroundColor="#292929" class="primaryB" position="Right" title="Grain" offsetOrigin="TopRight" width="130" enableSelection="true"></RadLegendView>     
        </RadPieChart>`

chartData.chart
` chartData.chart = {
            grainName: string,
            grainVol: number,
        }`

**Comment by quinnban** [comment]
I figured out the problem, turns out that one of the chart numbers negative.
