### ISSUE TITLE
Radlist view error: cannot read property '0' of undefined

### ISSUE THREAD

**Issue by adekunle11** [NativeScript/nativescript-ui-feedback#1409]
Hello,
i'm build my android app with Nativescript core(javascript),
i used radlist view on my search results page, the items displyed in the listview can be clicked.

The issue i have is:
when an item is tapped in the listview, it goes to the next page as it is supposed to, but when i click on the back button, it goes back to the previous page and reloads the list. while the list is reloading, if an item is tapped, i get the error: cannot read property '0' of undefined. is there a way i can stop this list from reloading when i navigate back to the page or can i get rid of the error and let the list reload.

This is the stacktrace:

```
An uncaught Exception occurred on "main" thread.
Calling js method onItemClick failed
TypeError: Cannot read property '0' of undefined

StackTrace:
push.../node_modules/nativescript-ui-listview/ui-listview.common.js.RadListView.getItemAtIndex(file:///data/data/org.nativescript.playjs/files/app/vendor.js:75480:26)
	at ListViewItemClickListenerImpl.onItemClick(file:///data/data/org.nativescript.playjs/files/app/vendor.js:76644:88)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at java.lang.Object_vendor_76632_36_ListViewItemClickListenerImpl.onItemClick(java.lang.Object.java)
	at com.telerik.widget.list.RadListView.notifyOnTapUp(RadListView.java:746)
	at com.telerik.widget.list.RadListView.notifyOnTapUp(RadListView.java:755)
	at com.telerik.widget.list.ListViewGestureListener.onTapUp(ListViewGestureListener.java:191)
	at com.telerik.widget.list.ListViewGestureListener.onSingleTapUp(ListViewGestureListener.java:290)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:604)
	at com.telerik.widget.list.ListViewGestureListener.onTouchEvent(ListViewGestureListener.java:165)
	at com.telerik.widget.list.RadListView.onTouchEvent(RadListView.java:555)
	at android.view.View.dispatchTouchEvent(View.java:9059)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:615)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2559)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2866)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2520)
	at android.view.View.dispatchPointerEvent(View.java:9277)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4739)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4577)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4234)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4291)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4154)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4120)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4128)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4101)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6597)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6487)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6687)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:5940)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by ray007** [comment]
This looks very similar to the error I got after upgrading `nativescript-ui-listview` from `8.2.0` to `9.0.1`:

```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-listview/ui-listview.common.js(file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-listview\ui-listview.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-listview/ui-listview.js(file:///data/data/com.loytec.lweb804/files/app/vendor.js:87032:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-listview/vue/index.js(file: node_modules\nativescript-ui-listview\vue\index.js:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: app\app.js:2:0)
System.err:     at ./app.js(file:///data/data/com.loytec.lweb804/files/app/bundle.js:1879:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/com.loytec.lweb804/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-listview/ui-listview.common.js(file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-listview\ui-listview.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-listview/ui-listview.js(file:///data/data/com.loytec.lweb804/files/app/vendor.js:87032:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-listview/vue/index.js(file: node_modules\nativescript-ui-listview\vue\index.js:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: app\app.js:2:0)
System.err:     at ./app.js(file:///data/data/com.loytec.lweb804/files/app/bundle.js:1879:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/com.loytec.lweb804/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6227)
System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:237)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:214)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err: File: (file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:
System.err: StackTrace:
System.err: ../node_modules/nativescript-ui-listview/ui-listview.common.js(file: node_modules\nativescript-ui-listview\ui-listview.common.js:65:44)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: node_modules\nativescript-ui-listview\ui-listview.android.js:1:0)
System.err:     at ../node_modules/nativescript-ui-listview/ui-listview.js(file:///data/data/com.loytec.lweb804/files/app/vendor.js:87032:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/nativescript-ui-listview/vue/index.js(file: node_modules\nativescript-ui-listview\vue\index.js:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: app\app.js:2:0)
System.err:     at ./app.js(file:///data/data/com.loytec.lweb804/files/app/bundle.js:1879:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at checkDeferredModules(file: app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/com.loytec.lweb804/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err:
System.err:
System.err: TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:674)
System.err:     at com.tns.Runtime.run(Runtime.java:666)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6222)
System.err:     ... 8 more
```

I had also upgraded nativescript android from `6.5.1` to `6.5.3` and I'm still working on getting a non-crashing state again...
